version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gateway:
    build:
      context: ./apps/gateway
    container_name: gateway
    environment:
      - JWT_SECRET=maplestory
      - JWT_EXPIRES_IN=60s
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - event

  auth:
    build:
      context: ./apps/auth
    container_name: auth
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=maplestory
      - JWT_EXPIRES_IN=60s
    depends_on:
      - mongo

  event:
    build:
      context: ./apps/event
    container_name: event
    environment:
      - MONGODB_URI=mongodb://mongo:27017/event
    depends_on:
      - mongo

volumes:
  mongo_data:
