# Gateway Service Endpoints

### Health Check
### @name health
GET http://localhost:3000/health

### Sign Up
### @name signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "auditor@maplestory.com",
    "password": "healme777",
    "name": "healman",
    "loginType": "credentials"
}

### Sign In - User
### @name signinUser
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "healer003@gmail.com",
    "password": "healme777",
    "loginType": "credentials"
}

### Sign In - AUDITOR
### @name signinAuditor
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "auditor@maplestory.com",
    "password": "healme777",
    "loginType": "credentials"
}

### Sign In - Admin
### @name signinAdmin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "healer@gmail.com",
    "password": "healme777",
    "loginType": "credentials"
}


### ==============================================
### Update User Role
### @name updateUserRole
POST http://localhost:3000/auth/user/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI2MGY2MGE3NjhlOWM4Y2E4MzQxNDYiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzQ3MjU3NywiZXhwIjoxNzQ3NDcyNjM3fQ.pX4b647oCLkeWTs9TkfCYZp_fl-N-qsI1rwDuWoBtxE

{
    "userId": "68261f0863a0daf8f015363d",
    "newRole": "USER"
}

### Get User by ID
### @name getUserById
GET http://localhost:3000/auth/user/68261f0863a0daf8f015363d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI2MGY2MGE3NjhlOWM4Y2E4MzQxNDYiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzQ3MjU3NywiZXhwIjoxNzQ3NDcyNjM3fQ.pX4b647oCLkeWTs9TkfCYZp_fl-N-qsI1rwDuWoBtxE


### Create Reward Item
### @name createRewardItem
POST http://localhost:3000/event/reward/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzQ5NzkzMywiZXhwIjoxNzQ3NDk3OTkzfQ.ru9NqZL2tBbqsAgFC6Fhhzsh47ok30nPeAAdWHjw9L4

{
    "item": "포인트",
    "quantity": 100
}

### Create Reward
### @name createReward
POST http://localhost:3000/event/reward
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzQ5NzkzMywiZXhwIjoxNzQ3NDk3OTkzfQ.ru9NqZL2tBbqsAgFC6Fhhzsh47ok30nPeAAdWHjw9L4

{
    "title": "포인트 100 보상",
    "description": "포인트 100을 주는 보상입니다.",
    "rewardItemIds": ["6828b3d6dd87440f1d467540"]
}


### Create Event
### @name createEvent
POST http://localhost:3000/event
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzU1ODIzMSwiZXhwIjoxNzQ3NTU4MjkxfQ.f6sMdXw0tUwYEkSNSMPyueEgIynpwuHdM63KzZgYldE

{
    "title": "7로그인 700포인트 이벤트",
    "description": "7일 연속 접속 시 700포인트를 보상으로 드리는 이벤트입니다.",
    "category": "LOGIN",
    "triggerType": "STREAK",
    "goal": 7,
    "startDate": "2025-05-10",
    "endDate": "2025-06-15",
    "rewardIds": ["6828a847736f5cdec605559a"]
}

### Add Reward To Event
### @name addRewardToEvent
POST http://localhost:3000/event/68299f62b34579086d71c45c/reward/6828b3dfdd87440f1d467542
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzU1ODIzMSwiZXhwIjoxNzQ3NTU4MjkxfQ.f6sMdXw0tUwYEkSNSMPyueEgIynpwuHdM63KzZgYldE


### Get Event List
### @name getEventList
GET http://localhost:3000/event
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzQ5NzkzMywiZXhwIjoxNzQ3NDk3OTkzfQ.ru9NqZL2tBbqsAgFC6Fhhzsh47ok30nPeAAdWHjw9L4

### Get Event by ID
### @name getEventById

GET http://localhost:3000/event/6828b3ecdd87440f1d467544
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzQ5NzkzMywiZXhwIjoxNzQ3NDk3OTkzfQ.ru9NqZL2tBbqsAgFC6Fhhzsh47ok30nPeAAdWHjw9L4t

### Get Reward by ID
### @name getRewardById

GET http://localhost:3000/event/reward/6828a847736f5cdec605559a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzU4NzUyNCwiZXhwIjoxNzQ3NTg3NTg0fQ.yviZSrB0v9lODdc_6HVeGJTG0soLiVv6mEqOUtLJATQ


### Add Reward Item To Reward
### @name addRewardItemToReward

POST http://localhost:3000/event/reward/6828a847736f5cdec605559a/item/68289ea9aed5409799e37f1c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJ1c2VySWQiOiI2ODI4Njc3OGNiMTlhMTdlMTEzODI3YTEiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0NzU1ODcyNSwiZXhwIjoxNzQ3NTU4Nzg1fQ.LxgO4v1mAuNcFJSuYSdvc_uyvXT-mVtk1UyeYJmmoyo



### Claim Reward
### @name claimReward
POST http://localhost:3000/event/682992218a3bcf4ee3ff5b0d/claim-reward
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc2Y2NiMTlhMTdlMTEzODI3OWUiLCJ1c2VySWQiOiI2ODI4Njc2Y2NiMTlhMTdlMTEzODI3OWUiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyMDAzQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQ3NTc2NDAwLCJleHAiOjE3NDc1NzY0NjB9.08gq_sv6TJ4_4aQbjgPLvhkWYjJ0uFTYRa1SmUinrCA

### getMyClaimHistory
### @name getMyClaimHistory
GET http://localhost:3000/event/68298ed2c17e7ce3149a5c45/reward/claim-history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc2Y2NiMTlhMTdlMTEzODI3OWUiLCJ1c2VySWQiOiI2ODI4Njc2Y2NiMTlhMTdlMTEzODI3OWUiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyMDAzQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQ3NTc3ODMyLCJleHAiOjE3NDc1Nzc4OTJ9.-ch40M4T9ay4Umc0ccx3y9CJ3r6VA7T2rBuQvRA2VJU


### search Claim History
### @name searchClaimHistory
GET http://localhost:3000/event/reward/claim-history?userId=6828676ccb19a17e1138279e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODI4Njc2Y2NiMTlhMTdlMTEzODI3OWUiLCJ1c2VySWQiOiI2ODI4Njc2Y2NiMTlhMTdlMTEzODI3OWUiLCJuYW1lIjoiaGVhbG1hbiIsImVtYWlsIjoiaGVhbGVyMDAzQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQ3NTc5MTczLCJleHAiOjE3NDc1NzkyMzN9.wI3JtdqT4mKANcvmTJ8KvfJbDqUNRzTlA7dBYCFiKzE